services:
  raptron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raptron-site
    ports:
      - "9500:9500"
    restart: unless-stopped
    environment:
      - ODOO_API_KEY=02d9da50eab815e491894e0901e798d4762a3ef6
      - ODOO_BASE_URL=https://hq.syscomatic.com
