/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TermsOfServiceRouteImport } from "./routes/terms-of-service";
import { Route as RequestDemoRouteImport } from "./routes/request-demo";
import { Route as PrivacyPolicyRouteImport } from "./routes/privacy-policy";
import { Route as CookiePolicyRouteImport } from "./routes/cookie-policy";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as CaseStudiesRouteImport } from "./routes/case-studies";
import { Route as BookConsultationRouteImport } from "./routes/book-consultation";
import { Route as BlogRouteImport } from "./routes/blog";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ServicesIndexRouteImport } from "./routes/services.index";
import { Route as ServicesSlugRouteImport } from "./routes/services.$slug";

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
} as any);
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: "/request-demo",
  path: "/request-demo",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any);
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: "/cookie-policy",
  path: "/cookie-policy",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: "/case-studies",
  path: "/case-studies",
  getParentRoute: () => rootRouteImport,
} as any);
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: "/book-consultation",
  path: "/book-consultation",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogRoute = BlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: "/services/",
  path: "/services/",
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: "/services/$slug",
  path: "/services/$slug",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/blog": typeof BlogRoute;
  "/book-consultation": typeof BookConsultationRoute;
  "/case-studies": typeof CaseStudiesRoute;
  "/contact": typeof ContactRoute;
  "/cookie-policy": typeof CookiePolicyRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/request-demo": typeof RequestDemoRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/services/$slug": typeof ServicesSlugRoute;
  "/services/": typeof ServicesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/blog": typeof BlogRoute;
  "/book-consultation": typeof BookConsultationRoute;
  "/case-studies": typeof CaseStudiesRoute;
  "/contact": typeof ContactRoute;
  "/cookie-policy": typeof CookiePolicyRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/request-demo": typeof RequestDemoRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/services/$slug": typeof ServicesSlugRoute;
  "/services": typeof ServicesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/blog": typeof BlogRoute;
  "/book-consultation": typeof BookConsultationRoute;
  "/case-studies": typeof CaseStudiesRoute;
  "/contact": typeof ContactRoute;
  "/cookie-policy": typeof CookiePolicyRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/request-demo": typeof RequestDemoRoute;
  "/terms-of-service": typeof TermsOfServiceRoute;
  "/services/$slug": typeof ServicesSlugRoute;
  "/services/": typeof ServicesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/blog"
    | "/book-consultation"
    | "/case-studies"
    | "/contact"
    | "/cookie-policy"
    | "/privacy-policy"
    | "/request-demo"
    | "/terms-of-service"
    | "/services/$slug"
    | "/services/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/blog"
    | "/book-consultation"
    | "/case-studies"
    | "/contact"
    | "/cookie-policy"
    | "/privacy-policy"
    | "/request-demo"
    | "/terms-of-service"
    | "/services/$slug"
    | "/services";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/blog"
    | "/book-consultation"
    | "/case-studies"
    | "/contact"
    | "/cookie-policy"
    | "/privacy-policy"
    | "/request-demo"
    | "/terms-of-service"
    | "/services/$slug"
    | "/services/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  BlogRoute: typeof BlogRoute;
  BookConsultationRoute: typeof BookConsultationRoute;
  CaseStudiesRoute: typeof CaseStudiesRoute;
  ContactRoute: typeof ContactRoute;
  CookiePolicyRoute: typeof CookiePolicyRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  RequestDemoRoute: typeof RequestDemoRoute;
  TermsOfServiceRoute: typeof TermsOfServiceRoute;
  ServicesSlugRoute: typeof ServicesSlugRoute;
  ServicesIndexRoute: typeof ServicesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms-of-service": {
      id: "/terms-of-service";
      path: "/terms-of-service";
      fullPath: "/terms-of-service";
      preLoaderRoute: typeof TermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/request-demo": {
      id: "/request-demo";
      path: "/request-demo";
      fullPath: "/request-demo";
      preLoaderRoute: typeof RequestDemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy-policy": {
      id: "/privacy-policy";
      path: "/privacy-policy";
      fullPath: "/privacy-policy";
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cookie-policy": {
      id: "/cookie-policy";
      path: "/cookie-policy";
      fullPath: "/cookie-policy";
      preLoaderRoute: typeof CookiePolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/case-studies": {
      id: "/case-studies";
      path: "/case-studies";
      fullPath: "/case-studies";
      preLoaderRoute: typeof CaseStudiesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/book-consultation": {
      id: "/book-consultation";
      path: "/book-consultation";
      fullPath: "/book-consultation";
      preLoaderRoute: typeof BookConsultationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/services/": {
      id: "/services/";
      path: "/services";
      fullPath: "/services/";
      preLoaderRoute: typeof ServicesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/services/$slug": {
      id: "/services/$slug";
      path: "/services/$slug";
      fullPath: "/services/$slug";
      preLoaderRoute: typeof ServicesSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookConsultationRoute: BookConsultationRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RequestDemoRoute: RequestDemoRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
